// https://github.com/median-dispersion/Software-Development-Icons

// This file was created by updateExample.py

// Icon HTML strings
const filled = `<div class="main-section-item"> <div class="main-section-item-icon" style="background-image: url('../Icons/Filled/Close.svg');"></div> <div class="main-section-item-text">Close.svg</div> </div><div class="main-section-item"> <div class="main-section-item-icon" style="background-image: url('../Icons/Filled/Code.svg');"></div> <div class="main-section-item-text">Code.svg</div> </div><div class="main-section-item"> <div class="main-section-item-icon" style="background-image: url('../Icons/Filled/Copy.svg');"></div> <div class="main-section-item-text">Copy.svg</div> </div><div class="main-section-item"> <div class="main-section-item-icon" style="background-image: url('../Icons/Filled/Delete.svg');"></div> <div class="main-section-item-text">Delete.svg</div> </div><div class="main-section-item"> <div class="main-section-item-icon" style="background-image: url('../Icons/Filled/Dot.svg');"></div> <div class="main-section-item-text">Dot.svg</div> </div><div class="main-section-item"> <div class="main-section-item-icon" style="background-image: url('../Icons/Filled/DragAndDrop.svg');"></div> <div class="main-section-item-text">DragAndDrop.svg</div> </div><div class="main-section-item"> <div class="main-section-item-icon" style="background-image: url('../Icons/Filled/Dropdown.svg');"></div> <div class="main-section-item-text">Dropdown.svg</div> </div><div class="main-section-item"> <div class="main-section-item-icon" style="background-image: url('../Icons/Filled/Menu.svg');"></div> <div class="main-section-item-text">Menu.svg</div> </div><div class="main-section-item"> <div class="main-section-item-icon" style="background-image: url('../Icons/Filled/Play.svg');"></div> <div class="main-section-item-text">Play.svg</div> </div><div class="main-section-item"> <div class="main-section-item-icon" style="background-image: url('../Icons/Filled/Radiation.svg');"></div> <div class="main-section-item-text">Radiation.svg</div> </div><div class="main-section-item"> <div class="main-section-item-icon" style="background-image: url('../Icons/Filled/Reload.svg');"></div> <div class="main-section-item-text">Reload.svg</div> </div><div class="main-section-item"> <div class="main-section-item-icon" style="background-image: url('../Icons/Filled/Search.svg');"></div> <div class="main-section-item-text">Search.svg</div> </div><div class="main-section-item"> <div class="main-section-item-icon" style="background-image: url('../Icons/Filled/Settings.svg');"></div> <div class="main-section-item-text">Settings.svg</div> </div><div class="main-section-item"> <div class="main-section-item-icon" style="background-image: url('../Icons/Filled/Stop.svg');"></div> <div class="main-section-item-text">Stop.svg</div> </div><div class="main-section-item"> <div class="main-section-item-icon" style="background-image: url('../Icons/Filled/User.svg');"></div> <div class="main-section-item-text">User.svg</div> </div>`;
const outlined = `<div class="main-section-item"> <div class="main-section-item-icon" style="background-image: url('../Icons/Outlined/Close.svg');"></div> <div class="main-section-item-text">Close.svg</div> </div><div class="main-section-item"> <div class="main-section-item-icon" style="background-image: url('../Icons/Outlined/Code.svg');"></div> <div class="main-section-item-text">Code.svg</div> </div><div class="main-section-item"> <div class="main-section-item-icon" style="background-image: url('../Icons/Outlined/Copy.svg');"></div> <div class="main-section-item-text">Copy.svg</div> </div><div class="main-section-item"> <div class="main-section-item-icon" style="background-image: url('../Icons/Outlined/Delete.svg');"></div> <div class="main-section-item-text">Delete.svg</div> </div><div class="main-section-item"> <div class="main-section-item-icon" style="background-image: url('../Icons/Outlined/Dot.svg');"></div> <div class="main-section-item-text">Dot.svg</div> </div><div class="main-section-item"> <div class="main-section-item-icon" style="background-image: url('../Icons/Outlined/DragAndDrop.svg');"></div> <div class="main-section-item-text">DragAndDrop.svg</div> </div><div class="main-section-item"> <div class="main-section-item-icon" style="background-image: url('../Icons/Outlined/Dropdown.svg');"></div> <div class="main-section-item-text">Dropdown.svg</div> </div><div class="main-section-item"> <div class="main-section-item-icon" style="background-image: url('../Icons/Outlined/Menu.svg');"></div> <div class="main-section-item-text">Menu.svg</div> </div><div class="main-section-item"> <div class="main-section-item-icon" style="background-image: url('../Icons/Outlined/Play.svg');"></div> <div class="main-section-item-text">Play.svg</div> </div><div class="main-section-item"> <div class="main-section-item-icon" style="background-image: url('../Icons/Outlined/Radiation.svg');"></div> <div class="main-section-item-text">Radiation.svg</div> </div><div class="main-section-item"> <div class="main-section-item-icon" style="background-image: url('../Icons/Outlined/Reload.svg');"></div> <div class="main-section-item-text">Reload.svg</div> </div><div class="main-section-item"> <div class="main-section-item-icon" style="background-image: url('../Icons/Outlined/Search.svg');"></div> <div class="main-section-item-text">Search.svg</div> </div><div class="main-section-item"> <div class="main-section-item-icon" style="background-image: url('../Icons/Outlined/Settings.svg');"></div> <div class="main-section-item-text">Settings.svg</div> </div><div class="main-section-item"> <div class="main-section-item-icon" style="background-image: url('../Icons/Outlined/Stop.svg');"></div> <div class="main-section-item-text">Stop.svg</div> </div><div class="main-section-item"> <div class="main-section-item-icon" style="background-image: url('../Icons/Outlined/User.svg');"></div> <div class="main-section-item-text">User.svg</div> </div>`;

// Once the page has finished loading
document.addEventListener("DOMContentLoaded", () => {

    // Inject the HTML at the end of the appropriate section
    document.getElementById("filled").insertAdjacentHTML("beforeend", filled);
    document.getElementById("outlined").insertAdjacentHTML("beforeend", outlined);

});